### ISSUE TITLE
Public comment not being imported

### ISSUE THREAD

**Issue by oculos** [eigenmagic/fediblockhole#33] opened 2023-01-21 10:45 UTC
Hi,

Public comments are not being imported here: 

```
2023-01-21 10:44:22,011 INFO Change detected. Need to update ['reject_media', 'reject_reports', 'obfuscate'] for domain block for nicecrew.digital
2023-01-21 10:44:22,011 INFO Old block definition: <DomainBlock {'domain': 'nicecrew.digital', 'severity': 'suspend', 'public_comment': '', 'private_comment': '', 'reject_media': True, 'reject_reports': True, 'obfuscate': True, 'id': '109'}>
2023-01-21 10:44:22,011 INFO Pushing new block definition: <DomainBlock {'domain': 'nicecrew.digital', 'severity': 'suspend', 'public_comment': '', 'private_comment': '', 'reject_media': False, 'reject_reports': False, 'obfuscate': False}>
2023-01-21 10:44:23,159 INFO Change detected. Need to update ['reject_media', 'reject_reports', 'obfuscate'] for domain block for ns.auction
2023-01-21 10:44:23,160 INFO Old block definition: <DomainBlock {'domain': 'ns.auction', 'severity': 'suspend', 'public_comment': '', 'private_comment': '', 'reject_media': True, 'reject_reports': True, 'obfuscate': True, 'id': '110'}>
2023-01-21 10:44:23,160 INFO Pushing new block definition: <DomainBlock {'domain': 'ns.auction', 'severity': 'suspend', 'public_comment': '', 'private_comment': '', 'reject_media': False, 'reject_reports': False, 'obfuscate': False}>
2023-01-21 10:44:24,318 INFO Change detected. Need to update ['reject_media', 'reject_reports', 'obfuscate'] for domain block for outpoa.st
2023-01-21 10:44:24,318 INFO Old block definition: <DomainBlock {'domain': 'outpoa.st', 'severity': 'suspend', 'public_comment': '', 'private_comment': '', 'reject_media': True, 'reject_reports': True, 'obfuscate': True, 'id': '111'}>
```

Even though they are included on the configurations.
Any tips to fix this?
Best,
Francis

**Comment by sgrigson** [comment] 2023-01-21 18:13
Just backing this up. In my case, I don't want the public comments but I noticed that they aren't being imported even when configured for it, at least not over public API links, *or* when I connect to my own server using a `read:blocks` permission. I haven't tried doing a full admin:read:domain_blocks permission to see if *that* pulls over public comments or if the issue is elsewhere.

I'm pulling a lot of data over public apis, and despite public reasons being available I've never actually included them in a file.

Just some more info for debugging.

**Comment by jpwarren** [comment] 2023-01-21 20:56
I found the problem: The JSON blocklist parser assumed that the Mastodon public API would use the same key for `public_comment` that the admin API uses. But it doesn't. It calls it `comment` instead. Because of course it does.

**Comment by jpwarren** [comment] 2023-01-21 21:01
Merged in a fix just now: [94f1063](https://github.com/eigenmagic/fediblockhole/commit/94f106333cec80c34e6e3e6c002429f1884a1294)

Works in testing. Check it out and see if this fixes the issue.

**Comment by sgrigson** [comment] 2023-01-21 21:51
I enabled importing of public_comments and got this:

```
Traceback (most recent call last):
  File "/usr/local/bin/fediblock-sync", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/fediblockhole/__init__.py", line 733, in main
    sync_blocklists(args)
  File "/usr/local/lib/python3.10/dist-packages/fediblockhole/__init__.py", line 74, in sync_blocklists
    merged = merge_blocklists(blocklists, conf.mergeplan)
  File "/usr/local/lib/python3.10/dist-packages/fediblockhole/__init__.py", line 206, in merge_blocklists
    blockdata = apply_mergeplan(merged[domain], newblock, mergeplan)
  File "/usr/local/lib/python3.10/dist-packages/fediblockhole/__init__.py", line 234, in apply_mergeplan
    blockdata[key] = merge_comments(oldcomment, newcomment)
  File "/usr/local/lib/python3.10/dist-packages/fediblockhole/__init__.py", line 302, in merge_comments
    new_tokens = newcomment.split(', ')
AttributeError: 'NoneType' object has no attribute 'split'
```

Note that several of these were from the public API, but one of the sources was from my server and used the non-admin `read:blocks` token. Not sure if that's relevant info.

**Comment by jpwarren** [comment] 2023-01-22 02:31
I've added some tests and updated the comment merge code to be more robust.

**Comment by sgrigson** [comment] 2023-01-23 15:42
That seems to have worked for me.

**Comment by jpwarren** [comment] 2023-01-24 19:51
Ace! I'll close this one out.

**Closed by jpwarren** 2023-01-24 19:51 UTC
